#!/usr/bin/env node
/* csp-inline.js — turn inline event-handler attributes into data attributes +
 * a generated handler table, and compute the CSP script hashes for every
 * inline <script> block. Lets the worker ship
 *   script-src 'self' 'sha256-…' … https://cdnjs.cloudflare.com https://cdn.jsdelivr.net
 * with NO 'unsafe-inline'.
 *
 * Why: the SPA had 244 inline handlers (onclick="…" etc.). CSP hashes cover
 * <script> element bodies, not attributes, so every one of them forced
 * 'unsafe-inline' — which also allows any injected <script> to run. With the
 * handlers moved into a hash-covered block, an injected script or attribute
 * is refused by the browser.
 *
 * How:
 *   1. every  on<evt>="CODE"  (in static HTML and inside JS string literals)
 *      becomes  data-h-<evt>="hN"  with the same quoting, and
 *      __H.hN = function(event){ CODE }  is emitted into one generated
 *      <script id="h-table"> before </body>. `this` is the element, `event`
 *      is in scope, `return false` cancels the default — same semantics as the
 *      attribute. Handlers whose CODE varies per element (template-string
 *      interpolation) cannot be tabled and must already have been rewritten
 *      by hand to data-h-<evt>="name" + data-* arguments; this script refuses
 *      to build if any remain.
 *   2. the dispatcher (in index.html itself, id="h-dispatch") delegates
 *      bubbling events from document and binds target-only events
 *      (mouseenter, mouseleave, focus, error) directly.
 *   3. sha256 of every inline script body → CSP source list.
 *
 * Exports: transform(html) → { html, count, names }, scriptHashes(html) → [ 'sha256-…' ]
 * CLI:     node csp-inline.js index.html   (prints counts and hashes; writes nothing)
 */
const crypto = require('crypto');

const ATTR_RE = /(\s)on([a-z]+)(\s*=\s*)(\\?["'])([\s\S]*?)\4/g;

function isDynamic(code) {
  return code.indexOf('${') !== -1 || /['"]\s*\+|\+\s*['"]/.test(code);
}

/* Undo the escaping the attribute lived under: HTML entities in static
 * markup, backslash-escapes inside a JS string literal. */
function unescapeCode(code, quote) {
  let c = code;
  if (quote.charAt(0) === '\\') {
    c = c.replace(/\\(["'\\])/g, '$1');
  } else {
    c = c.replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&apos;/g, "'").replace(/&lt;/g, '<').replace(/&gt;/g, '>').replace(/&amp;/g, '&');
    /* an attribute inside a JS string that used the OTHER quote style still
     * carries \' escapes for its own string context */
    c = c.replace(/\\'/g, "'");
  }
  return c;
}

function transform(html) {
  const table = new Map();   // code -> name
  const names = [];
  const dynamic = [];
  let count = 0;
  const out = html.replace(ATTR_RE, (m, ws, evt, eq, quote, code, offset) => {
    if (isDynamic(code)) { dynamic.push({ evt, code: code.slice(0, 80), line: html.slice(0, offset).split('\n').length }); return m; }
    count++;
    const body = unescapeCode(code, quote);
    let name = table.get(body);
    if (!name) { name = 'h' + (table.size + 1); table.set(body, name); names.push(name); }
    return `${ws}data-h-${evt}${eq}${quote}${name}${quote}`;
  });
  if (dynamic.length) {
    const err = new Error('csp-inline: ' + dynamic.length + ' inline handler(s) interpolate per-element values and cannot be tabled — rewrite them as data-h-<evt>="name" + data-* attributes:\n' +
      dynamic.map((d) => `  line ${d.line}: on${d.evt}="${d.code}"`).join('\n'));
    err.dynamic = dynamic; throw err;
  }
  const lines = [];
  for (const [body, name] of table) lines.push(`__H.${name}=function(event){${body}\n};`);
  const block = `<script id="h-table">/* generated by csp-inline.js — ${table.size} handler bodies for ${count} attributes */\nwindow.__H=window.__H||{};\n${lines.join('\n')}\n</script>`;
  const idx = out.lastIndexOf('</body>');
  const finalHtml = idx === -1 ? out + block : out.slice(0, idx) + block + '\n' + out.slice(idx);
  return { html: finalHtml, count, names, unique: table.size };
}

function scriptHashes(html) {
  const re = /<script\b([^>]*)>([\s\S]*?)<\/script>/gi;
  const hashes = [];
  let m;
  while ((m = re.exec(html)) !== null) {
    if (/\bsrc\s*=/.test(m[1] || '')) continue;
    const type = (/\btype\s*=\s*["']?([^"'\s>]+)/i.exec(m[1] || '') || [])[1];
    if (type && !/^(text\/javascript|application\/javascript|module)$/i.test(type)) continue;
    hashes.push("'sha256-" + crypto.createHash('sha256').update(m[2], 'utf8').digest('base64') + "'");
  }
  return hashes;
}

module.exports = { transform, scriptHashes, ATTR_RE };

if (require.main === module) {
  const fs = require('fs');
  const file = process.argv[2];
  if (!file) { console.error('usage: node csp-inline.js <index.html>'); process.exit(2); }
  const html = fs.readFileSync(file, 'utf8');
  try {
    const r = transform(html);
    const hashes = scriptHashes(r.html);
    console.log(`csp-inline: ${r.count} handler attributes → ${r.unique} tabled bodies; ${hashes.length} inline script hashes`);
  } catch (e) { console.error(e.message); process.exit(1); }
}
